<?php

namespace Lipagateways\Pesapal\app\Http\Controllers;

use Illuminate\Support\Facades\Auth;
use Lipagateways\Pesapal\app\Models\Pesapal;
use Lipagateways\Pesapal\app\Http\Requests\StorePesapalRequest;
use Lipagateways\Pesapal\app\Http\Requests\UpdatePesapalRequest;

class PesapalController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \App\Http\Requests\StorePesapalRequest  $request
     * @return \Illuminate\Http\Response
     */
    public function store(StorePesapalRequest $request)
    {
    //get form details<br>$amount = $_POST['amount'];
     $first_name = $request->firstName; //[optional]
     $last_name = $request->lastName; //[optional]
     $email = $request->email;
     $phonenumber = $request->phone; //ONE of email or phonenumber is required
     $amount = number_format(1500, 2);//format amount to 2 decimal places
     $desc = 'Inteli System Payment';
     $type = 'MERCHANT'; //default value = MERCHANT
     $reference = 'Inteli';//unique order id of the transaction, generated by merchant
    }


    public function callback(StorePesapalRequest $request)
    {

    }
    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Pesapal  $pesapal
     * @return \Illuminate\Http\Response
     */
    public function show(Pesapal $pesapal)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Pesapal  $pesapal
     * @return \Illuminate\Http\Response
     */
    public function edit(Pesapal $pesapal)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Http\Requests\UpdatePesapalRequest  $request
     * @param  \App\Models\Pesapal  $pesapal
     * @return \Illuminate\Http\Response
     */
    public function update(UpdatePesapalRequest $request, Pesapal $pesapal)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Pesapal  $pesapal
     * @return \Illuminate\Http\Response
     */
    public function destroy(Pesapal $pesapal)
    {
        //
    }
}
